#!/bin/sh

set -e

# Pass maintainer script parameters to hook scripts
export DEB_MAINT_PARAMS="$*"

# Tell initramfs builder whether it's wanted
export INITRD=Yes

test -d /etc/kernel/postrm.d && run-parts --arg="5.10.158-bt" --arg="/boot/vmlinuz-5.10.158-bt" /etc/kernel/postrm.d
exit 0
